services:
  email-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: email-server-smtp
    env_file:
      - .env
    ports:
      - "2525:2525"
      - "48080:48080"
    volumes:
      - ./emails:/root/emails
    restart: unless-stopped
